name: Run tests
on: [push]
jobs:
  Run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18.x']

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Installing Node Dependencies
        run: npm i

      - name: Setup firebase emulators and run test
        uses: w9jds/firebase-action@master
        with:
          args: emulators:exec \"npm run test:unit --exit\"
        env:
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
