name: Run tests
on: [push]
jobs:
  Run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18.x']

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Installing Node Dependencies
        run: npm i

      - name: Setup up firebase
        run: npm i firebase-tools -g

      - name: run test
        run: firebase emulators:exec --token ${{secrets.FIREBASE_TOKEN}} \"npm run test:unit\"
